version: '2'
services:
    appgeteway-app:
        image: appgeteway
        external_links:
            - appgeteway-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - appgeteway-cassandra:cassandra
            - appgeteway-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/appgeteway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    appgeteway-mysql:
        extends:
            file: mysql.yml
            service: appgeteway-mysql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: appgeteway-cassandra
    appgeteway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: appgeteway-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
